# bash runall.sh brca
bash runall.sh cesc
bash runall.sh chol
bash runall.sh coad
bash runall.sh dlbc
bash runall.sh esca
bash runall.sh gbm
bash runall.sh kich
bash runall.sh kirc
bash runall.sh kirp
bash runall.sh lgg
bash runall.sh meso
bash runall.sh ov
bash runall.sh paad
bash runall.sh pcpg
bash runall.sh prad
bash runall.sh read
bash runall.sh sarc
bash runall.sh skcm
bash runall.sh stad
bash runall.sh tgct
bash runall.sh thca
bash runall.sh thym
bash runall.sh ucec
bash runall.sh ucs
bash runall.sh uvm